---

- name: Edit VerneMQ Configuration File
  become: yes
  ini_file:
    dest: /etc/vernemq/vernemq.conf
    section: ~
    option: "{{ item.key }}"
    value: "{% if item.value == true %}on{% elif item.value == false %}off{% else %}{{ item.value }}{% endif %}"
  with_dict: "{{ sansible_vernemq_configuration }}"
  notify: reload vernemq

- name: Check VerneMQ Configuration Options
  become: yes
  command: vernemq chkconfig
  changed_when: no

- name: Start and enable VerneMQ for SysV
  become: yes
  service:
    name: vernemq
    state: started
    enabled: yes
  when: ansible_service_mgr != "systemd"

- name: Start and enable VerneMQ for SystemD
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    name: vernemq
    state: started
  when: ansible_service_mgr == "systemd"

- name: Get Cluster Status
  become: yes
  command: vmq-admin cluster show
  register: cluster_show
  changed_when: no
  when: sansible_vernemq_cluster_discovery_node is not none

- name: Join Cluster
  become: yes
  command: "vmq-admin cluster join discovery-node={{ sansible_vernemq_cluster_discovery_node }}"
  register: cluster_join
  when:
    - sansible_vernemq_cluster_discovery_node is not none
    - sansible_vernemq_cluster_discovery_node not in cluster_show.stdout
