---

- name: Edit VerneMQ Configuration File
  become: yes
  community.general.ini_file:
    dest: /etc/vernemq/vernemq.conf
    mode: "0644"
    option: "{{ item.key }}"
    section: ~
    value: "{{ item.value }}"
  with_dict: "{{ sansible_vernemq_configuration }}"
  notify: reload vernemq

- name: Check VerneMQ Configuration Options
  become: yes
  ansible.builtin.command: vernemq chkconfig
  changed_when: no

- name: Start and enable VerneMQ for SystemD
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    name: vernemq
    state: started

- name: Ensure VerneMQ Configuration Changes are in Effect Before Cluster Checks
  meta: flush_handlers

- name: Get Cluster Status
  become: yes
  ansible.builtin.command: vmq-admin cluster show
  register: cluster_show
  changed_when: no
  when: sansible_vernemq_cluster_discovery_node is not none

- name: Join Cluster
  become: yes
  ansible.builtin.command: "vmq-admin cluster join discovery-node={{ sansible_vernemq_cluster_discovery_node }}"
  register: cluster_join
  when:
    - sansible_vernemq_cluster_discovery_node is not none
    - sansible_vernemq_cluster_discovery_node not in cluster_show.stdout
