---

- name: Converge Node One
  gather_facts: yes
  hosts: node_one
  roles:
    - role: vernemq
      sansible_vernemq_configuration:
        accept_eula: "yes"
        allow_anonymous: "on"
        distributed_cookie: moleculetest
        listener.vmq.clustering: "{{ ansible_eth0.ipv4.address }}:44053"
        nodename: "{{ ansible_hostname }}@{{ ansible_eth0.ipv4.address }}"

- name: Converge Other Nodes
  gather_facts: yes
  hosts: other_nodes

  vars:
    group_os_name: "{{ inventory_hostname.split('-')[1] }}"

  roles:
    - role: vernemq
      sansible_vernemq_cluster_discovery_node: "vernemq-{{ group_os_name }}-1@{{ hostvars['vernemq-' + group_os_name + '-1'].ansible_eth0.ipv4.address }}"
      sansible_vernemq_configuration:
        accept_eula: "yes"
        allow_anonymous: "on"
        distributed_cookie: moleculetest
        listener.vmq.clustering: "{{ ansible_eth0.ipv4.address }}:44053"
        nodename: "{{ ansible_hostname }}@{{ ansible_eth0.ipv4.address }}"
