---

driver:
  name: docker

platforms:
  - name: vernemq-xenial-1
    image: jrei/systemd-ubuntu:16.04
    groups:
      - xenial
      - node_one
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: vernemq-xenial-2
    image: jrei/systemd-ubuntu:16.04
    groups:
      - xenial
      - other_nodes
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: vernemq-xenial-3
    image: jrei/systemd-ubuntu:16.04
    groups:
      - xenial
      - other_nodes
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: vernemq-bionic-1
    image: jrei/systemd-ubuntu:18.04
    groups:
      - bionic
      - node_one
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: vernemq-bionic-2
    image: jrei/systemd-ubuntu:18.04
    groups:
      - bionic
      - other_nodes
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: vernemq-bionic-3
    image: jrei/systemd-ubuntu:18.04
    groups:
      - bionic
      - other_nodes
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint --exclude molecule
  flake8 molecule/

dependency:
  name: galaxy

scenario:
  name: default

verifier:
  name: testinfra
