---

- name: Converge Node One
  gather_facts: yes
  hosts: node_one
  roles:
    - role: vernemq
      sansible_vernemq_configuration:
        allow_anonymous: yes
        distributed_cookie: moleculetest
        listener.vmq.clustering: "{{ ansible_eth0.ipv4.address }}:44053"
        nodename: "{{ ansible_hostname }}@{{ ansible_eth0.ipv4.address }}"

- name: Converge Other Nodes
  gather_facts: yes
  hosts: other_nodes
  roles:
    - role: vernemq
      sansible_vernemq_cluster_discovery_node: "vernemq-{{ group_names[1] }}-1@{{ hostvars['vernemq-' + group_names[1] + '-1'].ansible_eth0.ipv4.address }}"
      sansible_vernemq_configuration:
        allow_anonymous: yes
        distributed_cookie: moleculetest
        listener.vmq.clustering: "{{ ansible_eth0.ipv4.address }}:44053"
        nodename: "{{ ansible_hostname }}@{{ ansible_eth0.ipv4.address }}"
